/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ChallengeChallengeIdImport } from './routes/challenge/$challengeId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ChallengeChallengeIdRoute = ChallengeChallengeIdImport.update({
  id: '/challenge/$challengeId',
  path: '/challenge/$challengeId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/challenge/$challengeId': {
      id: '/challenge/$challengeId'
      path: '/challenge/$challengeId'
      fullPath: '/challenge/$challengeId'
      preLoaderRoute: typeof ChallengeChallengeIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenge/$challengeId': typeof ChallengeChallengeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenge/$challengeId': typeof ChallengeChallengeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/challenge/$challengeId': typeof ChallengeChallengeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/challenge/$challengeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/challenge/$challengeId'
  id: '__root__' | '/' | '/challenge/$challengeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengeChallengeIdRoute: typeof ChallengeChallengeIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengeChallengeIdRoute: ChallengeChallengeIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/challenge/$challengeId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/challenge/$challengeId": {
      "filePath": "challenge/$challengeId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
